### ISSUE TITLE
Repeaters seem to stay on for too long

### ISSUE THREAD

**Issue by InventivetalentDev** [InventivetalentDev/AdvancedRepeaters#2]
Looks like the specified delay is applied to both the on and off cycle of the repeaters, instead of carrying over the input duration.

**Comment by Th3Shadowbroker** [comment]
>...carrying over the input duration.

Do you mean something like this? https://www.youtube.com/watch?v=K-LkWRT33-A

**Comment by InventivetalentDev** [comment]
> Do you mean something like this? https://www.youtube.com/watch?v=K-LkWRT33-A

Yes! 
A config option to toggle the functionality would probably be nice too, for those used to the old behavior :3

**Comment by Th3Shadowbroker** [comment]
Great 👍 
I'll try to make a PR over ~~the day~~ over the weekend.
As you already said, the bukkit redstone events aren't really good 😂
I have one more idea I'll try.

**Comment by Th3Shadowbroker** [comment]
Okay. I've played around with different approaches for quite a while now. However, the BlockRedstoneEvent is fired everytime a signal comes in or the repeater changes his state to powered and it would require a lot more code and time for testing etc. to keep the actual input-duration. As an alternative I will open a PR that implements custom active-time defined in line 3 of the sign wich, in my opinion adds more customizability for the user. The approach I've tried in the video only worked with 0 durations and I have to admit I were a bit too optimistic to get it easily working with longer durations without the said amount of code and time.

EDIT: I hope there will be more detailed redstone events in the future ^^

**Comment by InventivetalentDev** [comment]
I ended up playing around with the event a bit more and managed to get to to carry over the original pulse length: 
https://i.imgur.com/3dG1mkR.gifv

I really like the option that you can specify how long it stays on though, so I'll try to keep that included!

**Comment by Th3Shadowbroker** [comment]
Great! Just an idea but you could check for valueOut > -1 as well as the config value you wanted to add. If no "active-time" is defined the input duration will be carried over if enabled in the config.

**Comment by Th3Shadowbroker** [comment]
79efa35b7ef13c40cffb2ede923e391b4c2ca0e5: By far less code than I expected 👍 
Well I guess I got totally stuck with my approach on carrying over the signals 😂
